#!/bin/sh


dateRun="$(date)"
echo $dateRun '  Runned  Install Update Upgrade'


sudo mkdir /etc/Telenor
sudo chown 777 pi:pi /etc/Telenor

git clone git://github.com/diegoc16/little_bit_of_everything  /etc/Telenor/

sudo mv /etc/Telenor/little_bit_of_everything /etc/Telenor/
sudo rm -rf /etc/Telenor/little_bit_of_everything

sudo chmod 777 /etc/Telenor/runUdpServer.sh
sudo chmod 777 /etc/Telenor/sunUdpClient.sh
sudo chmod 777 /etc/Telenor/changeHost.sh
sudo chmod 777 /etc/Telenor/udpServer.py

sudo apt-get update
sudo apt-get upgrate -y

sudo apt-get install -y isc-dhcp-server
sudo pip3 install netifaces
sudo easy_install3 pip
sudo apt-get install -y nmap

sudo rm /etc/dhcp/dhcpd.config
sudo mv /etc/Telenor/dhcpd.config /etc/dhcp/   

