#!/bin/bash

#dateRun="$(date)"
#echo $dateRun '  Runned  /etc/Telenor/runudpclient.sh'

#echo "Positional parameter"
#echo '$0 =  ' $0
#echo '$1 =  ' $1
#echo '$2 =  ' $2
#echo '$3 =  ' $3
#echo '$4 =  ' $4

#echo "You start with $# positional parameters"

########################################################################
#  Iperf TCP uses following parameters as default:
#
# -p 9099   =  port number 9099
# -c IP     = Target IP, it should be the server IP
# -f K      = format: bits(b), bytes(B), kilobits(k), kilobytes(K),
#             megabits(m), megabytes(M), gigabits(g) or gigabytes(G).
# -r ''     = Bi-directional bandwidth measurement
# -d ''     = Simultaneous bi-directional bandwidth measurement:
# -w 80000  = The TCP window size is the amount of data that can be
#             buffered during a connection without a validation from the receiver.
# -t 10     = -t argument specifies the test duration time in seconds, default is 10 secs.
# -i 99999  = -i argument indicates the interval in seconds between periodic bandwidth reports.
########################################################################
#28
targetIP='10.168.74.115'
port=9099
format='K'
bidirectional_r=''
dual_d=''
wndw_size=80000
timee=10
intervel=99999

while [ "$1" != "" ]; do
    case $1 in
        -p | --port )           shift
                                port=$1
                                ;;
        -f | --format )         shift
                                format=$1
                                ;;
        -r | --tradeoff )       bidirectional_r='-r'
                                ;;
        -d | --dualtest )       dual_d='-d'
                                ;;
        -w | --window )         shift
                                wndw_size=$1
                                ;;
        -m | --multiplicator )  shift
                                multiplicator=$1
                                ;;
        -i | --interval )       shift
                                minterval=$1
                                ;;
        -t | --time )           shift
                                timee=$1
                                ;;
        * )
                                exit 1
    esac
    shift
done
#82



#delay=0
#declare -a packets=(55 40 30 25 20 10 5)
#declare -a sizes=(200 400 800 1600 3200 3200 6400)
declare -a delay=(1 2 3 4 5 6 7 8 9)

#clear
for number in 0 1 2 3 4 5 6
do


#(sleep $delay && sudo ping $targetIP -i $interval -I $interface -c $count -s $size)

#size=$((${sizes[$number]}*$multiplicator))
#delay=$(($number*2))

echo 'sleep '${delay[number]} '&& sudo iperf -c '$targetIP' -p '$port' -f '$format' '$bidirectional_r' '$dial_d' $
#(sleep $delay && sudo ping $targetIP -i $interval -I $interface -c ${packets[number]} -s $size &> /dev/null) &

done
exit 0
